version: '2'
services:

  mysql:
    container_name: test-mysql
    image: mysql:5.7.14
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'test-database'
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./.docker/data/mysql/:/docker-entrypoint-initdb.d
